### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by marcusjk** [socialveo/socialveo-issues-tracking#26]
where do you go to see FAQ page if you are logged into your profile

**Comment by andreakru** [comment]
Good question.
A part from guest pages, user receive a welcome email with link to faq, as below screenshot:
![screen shot 2016-10-06 at 16 40 49](https://cloud.githubusercontent.com/assets/5359394/19156976/03984120-8be4-11e6-852e-c7faa691d8e0.png)

But we need to add menu to static pages somewhere, maybe on left or right sidebar like facebook:

![screen shot 2016-10-06 at 16 41 28](https://cloud.githubusercontent.com/assets/5359394/19157004/23b5259a-8be4-11e6-823c-854de3df9995.png)
