### ISSUE TITLE
follow someone 

### ISSUE THREAD

**Issue by marcusjk** [socialveo/socialveo-issues-tracking#27]
can you give me a better idea of how someone will just follow someones profile right now i can see add a friend button but no follow button that i can see when visiting a new persons profile

**Comment by andreakru** [comment]
We are working to improve this, so you can better understand this.

Check how work google plus, we plan to make similar.

In google plus there is button "Follow". In socialveo will be "Connect" (or any other that you want).

When you click on Follow on google plus, then you start follow that person. If also other person start follow you, then you become friends (circle in google plus).

The same way in socialveo.

**Comment by marcusjk** [comment]
Think i get it so are you going to give them options like google+ 1 follow 2 family 3 friends and so forth

**Comment by andreakru** [comment]
Yes right, something like google circles.

**Comment by marcusjk** [comment]
that could work well give them a popup menu like google+ for them to pick which one to put that person or biz in

**Comment by andreakru** [comment]
Yes right, we plan make like popup menu of g+

**Comment by marcusjk** [comment]
what is the plan  for people to see  who's in the circles write now you just have  a list under users on the menu bar

**Comment by andreakru** [comment]
We plan to show this if users allow, something like /users page but inside user profile.
