### ISSUE TITLE
chat 

### ISSUE THREAD

**Issue by marcusjk** [socialveo/socialveo-issues-tracking#28]
Works good one thing when the first person leaves the chat who started the chat i.e. Marcus to rowstreet and row try's to respond after it dose not show up in marcus's message box

**Comment by andreakru** [comment]
If someone leave a chat, he will not anymore receive notifications from that conversation.
You need to create a new conversation, or add again your friends who leave chat.

Facebook don't allow to leave a one-to-one conversation, and if you leave a group conversation, then is archivied.

But in this case you have many conversations with your friends, and not just single thread like facebook.

**Comment by macagoraga** [comment]
We are going to improve this. You can leave only group chat, but not one-to-one. 
Plus you can see archivied message in a separated page like socialveo.co/messages
