### ISSUE TITLE
chat message

### ISSUE THREAD

**Issue by marcusjk** [socialveo/socialveo-issues-tracking#30]
Is there a way to stop the message deleting after someone opens it from chat  that's what it ls doing now

**Comment by andreakru** [comment]
Can you please explain a bit more, I am not sure what you mean. You can make a screenshot. Thanks

**Comment by marcusjk** [comment]
OK when you post something in a chat the person your chatting with gets a new message in there message box at the top of the page but when you open the message it deletes it and its no longer in your message box do think its better if the system deletes the message or the user has to like in notifications

**Comment by mervick** [comment]
Notification area shows only new messages, 
After that you have read these messages, logically, you no longer need this notifications, 
but you can always view the messages in the chat.

**Comment by marcusjk** [comment]
i see what you mean thanks
