### ISSUE TITLE
event

### ISSUE THREAD

**Issue by wlongdonstudio** [socialveo/socialveo-issues-tracking#34]
how to add an event to website?

**Comment by andreakru** [comment]
At the moment there is not this feature, but we can add it future network type event.
For now you could just create a network type group for this.

**Comment by wlongdonstudio** [comment]
Hmm this is a must for Mr. What's the eta?

**Comment by wlongdonstudio** [comment]
Typo..Hmm this is a must for mr What's the ETA?

**Comment by andreakru** [comment]
At the moment we don't have an ETA for this feature, but I will update you asap.
