### ISSUE TITLE
admin login screen

### ISSUE THREAD

**Issue by wlongdonstudio** [socialveo/socialveo-issues-tracking#45]
socialveo is the logo present at my admin login screen please replace with my logo. That logo is also there once i login in the admin area. How do i replace it myself?

https://www.dropbox.com/s/18xabmt8qgvhfjf/Screenshot%202017-01-04%2005.05.22.png?dl=0

**Comment by andreakru** [comment]
We will update logo of admin

**Comment by wlongdonstudio** [comment]
done?

**Comment by andreakru** [comment]
I have open issue for this request, we will change logo
