### ISSUE TITLE
After signup form get error

### ISSUE THREAD

**Issue by wlongdonstudio** [socialveo/socialveo-issues-tracking#6]
Get this error
 https://www.dropbox.com/s/x7ornndhxv2mdep/Screenshot_20160831-010444.png?dl=0

**Comment by wlongdonstudio** [comment]
Using notes 5 android
Pressed back and then hit sign in ot allowed me in

**Comment by wlongdonstudio** [comment]
After i hit activate account from my email i got this error
https://www.dropbox.com/s/uveb0pq8cg0mlc0/Screenshot_20160831-014245.jpg?dl=0

**Comment by andreakru** [comment]
Thanks for report. Seem that on demo is missing a widget. Let me check and update demo.

**Comment by wlongdonstudio** [comment]
updated from 4 days ago?

**Comment by andreakru** [comment]
Sorry for delay, I forgot update this ticket.
This issue is already fixed days ago.

You don't need to active account, on demo is disabled.
After registration, just login.
