### ISSUE TITLE
wrong profile pic

### ISSUE THREAD

**Issue by marcusjk** [socialveo/socialveo-issues-tracking#7]
Ok if i sign in as marcus and then go to someone else's profile say rowstreet and go to look at there pics or videos instead of the profile pics being rowstreets it changes it to my profile pics even though i am looking at rowstreets pics or videos it should be rowstreets profile pics and not marcus profile pics

**Comment by mervick** [comment]
ref https://github.com/socialveo/socialveo-issues-tracking/issues/1
